export const FORM_TAGS = {
    lets_sell_your_home: "lets_sell_your_home",
    lets_find_dream_home: "lets_find_dream_home",
    sell_timeline: "sell_timeline",
    sell_relationship: "sell_relationship",
    sell_agent_instant: "sell_agent_instant",
    sell_agent_contact: "sell_agent_contact",
    sell_owner: "sell_owner",
    sell_yagreement: "sell_yagreement",
    sell_instant_contact: "sell_instant_contact",
    sell_instant_calendar: "sell_instant_calendar",
    buy_motivation: "buy_motivation",
    buy_next: "buy_next",
    buy_browse: "buy_browse",
    buy_learn: "buy_learn",
    buy_advice: "buy_advice",
    buy_learn_heh: "buy_learn_heh",
    buy_contact_info: "buy_contact_info",
    instant_relationship: "instant_relationship",
    instant_contact: "instant_contact",
    sell_instant_calendar: "sell_instant_calendar",
    buy_calendar: "buy_calendar",
    sellbuy_calendar: "sellbuy_calendar",
    instant_calendar: "instant_calendar",
    get_started_sell: "get_started_sell",
    get_started_buy: "get_started_buy",
    get_started_buysell: "get_started_buysell",
    get_started_instant_offer: "get_started_instant_offer",

}